version: '3'

services:
  ev-charging-tracker:
    build: .
    container_name: ev-charging-tracker
    ports:
      - "5000:5000"
    volumes:
      # Mount the data directory to persist charging data
      - /portainer/Files/AppData:/app/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    
networks:
  default:
    driver: bridge